on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:
    branches:
      - main

name: Check Rust code
jobs:
  check:
    uses: msfjarvis/shared-workflows/.github/workflows/test-flakes-project.yml@a46da13fe6f953a7d5a8bc0ed061901dfc16e65b # main
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      cachix-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
