on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:
    branches:
      - main

name: Check Rust code
jobs:
  check:
    uses: msfjarvis/shared-workflows/.github/workflows/test-flakes-project.yml@462b646aee891ec0c64b08a152444d2c3faf3989 # main
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      cachix-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
